# Set tmux to use 256 colors and true color support 
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g status-style "bg=default"

# Enable mouse support
set -g mouse on

# Start windows and panes from 1, not 0
# uset -g base-index 1
# set -g pane-base-index 1
# set-window-option -g pane-base-index 1
# set-option -g renumber-windows on

# Set prefix keybind to Ctrl + Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'fabioluciano/tmux-tokyo-night'
# Tokyo Night Theme configuration
# set -g @theme_variation 'moon'
# set -g @theme_left_separator ''
# set -g @theme_right_separator ''
# set -g @theme_transparent_status_bar 'true'
# set -g @theme_transparent_left_separator_inverse ''
# set -g @theme_transparent_right_separator_inverse ''
set -g @theme_plugins 'datetime,weather,playerctl,yay'

set -g @plugin 'christoomey/vim-tmux-navigator'
# Vim Tmux Navigator configuration
set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# Set vi mode
set-window-option -g mode-keys vi

# Set keybindgs for yank plugin
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Open panes in current working directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
